# GoReleaser configuration for amail
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: amail
    main: ./cmd/amail
    binary: amail
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/thirteen37/amail/internal/cli.Version={{.Version}}
      - -X github.com/thirteen37/amail/internal/cli.GitCommit={{.ShortCommit}}
      - -X github.com/thirteen37/amail/internal/cli.BuildDate={{.Date}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: thirteen37
    name: amail
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
